/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userview;

import business.facilities.LibraryServices;
import business.person.Student;
import collegefunction.BalanceMoney;
import collegefunction.Report_DepartmentRank;
import collegefunction.University;
import collegefunction.department.StudentDetails;
import javax.swing.JOptionPane;

/**
 *
 * @author prane
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitpane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        libraryServicesButton = new javax.swing.JButton();
        collegePercentScoreButton = new javax.swing.JButton();
        transcriptButton = new javax.swing.JButton();
        balanceButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        picPanel = new javax.swing.JPanel();
        reportdataLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userProcessTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        userProcessTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Reports");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 37));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 0, -1, -1));

        libraryServicesButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        libraryServicesButton.setText("LMS");
        libraryServicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryServicesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(libraryServicesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 50));

        collegePercentScoreButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        collegePercentScoreButton.setText("College Score");
        collegePercentScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegePercentScoreButtonActionPerformed(evt);
            }
        });
        jPanel1.add(collegePercentScoreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 50));

        transcriptButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        transcriptButton.setText("Transcript");
        transcriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transcriptButtonActionPerformed(evt);
            }
        });
        jPanel1.add(transcriptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 223, 120, 50));

        balanceButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        balanceButton.setText("Balance");
        balanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(balanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 50));

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clearButton.setText("Clear All");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 70, -1));

        splitpane.setLeftComponent(jPanel1);

        picPanel.setBackground(new java.awt.Color(204, 204, 255));
        picPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("University Application"));

        userProcessTextArea.setColumns(20);
        userProcessTextArea.setRows(5);
        jScrollPane1.setViewportView(userProcessTextArea);

        userProcessTextArea2.setColumns(20);
        userProcessTextArea2.setRows(5);
        jScrollPane2.setViewportView(userProcessTextArea2);

        javax.swing.GroupLayout picPanelLayout = new javax.swing.GroupLayout(picPanel);
        picPanel.setLayout(picPanelLayout);
        picPanelLayout.setHorizontalGroup(
            picPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, picPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reportdataLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1569, 1569, 1569))
        );
        picPanelLayout.setVerticalGroup(
            picPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, picPanelLayout.createSequentialGroup()
                .addGroup(picPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, picPanelLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(reportdataLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(picPanelLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(picPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        splitpane.setRightComponent(picPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitpane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitpane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libraryServicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryServicesButtonActionPerformed
        // TODO add your handling code here:
            String report="";
            Student studentobj = new Student();
            LibraryServices ls = new LibraryServices();
            report = ls.getLibraryServicesReport(studentobj);
            userProcessTextArea.setText(report);
            userProcessTextArea2.setVisible(false);
            
    }//GEN-LAST:event_libraryServicesButtonActionPerformed

    private void collegePercentScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegePercentScoreButtonActionPerformed
            userProcessTextArea2.setVisible(true);
        Report_DepartmentRank r=new Report_DepartmentRank();
        
        String output=r.rankDept("C:\\Parth\\Project_AED\\gargava_parth_assignment04_ums\\student_data.xml");
        userProcessTextArea.setText(output);
        
String output1=r.rankDept("C:\\Parth\\Project_AED\\gargava_parth_assignment04_ums\\student_data2.xml");
        userProcessTextArea2.setText(output1);

        // TODO add your handling code here:
    }//GEN-LAST:event_collegePercentScoreButtonActionPerformed

    private void balanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButtonActionPerformed

BalanceMoney balanceMoney= new BalanceMoney();
String output=balanceMoney.findBalance("C:\\Parth\\Project_AED\\gargava_parth_assignment04_ums\\student_data3.xml");
         userProcessTextArea.setText(output);
        userProcessTextArea2.setText(" ");
        userProcessTextArea2.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_balanceButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

userProcessTextArea.setText("");
userProcessTextArea2.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void transcriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transcriptButtonActionPerformed

        StudentDetails stud=new StudentDetails();
        String campusID;
campusID = JOptionPane.showInputDialog("Campus ID : ");
        
 String h=  stud.viewStudentDetails("C:\\Parth\\Project_AED\\gargava_parth_assignment04_ums\\person_data.xml",campusID);
        userProcessTextArea.setText(h);
userProcessTextArea2.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_transcriptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        University u1= new University("MIT");
        University u2= new University("Harvard");
        University u3= new University("Boston University");
                
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton collegePercentScoreButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton libraryServicesButton;
    private javax.swing.JPanel picPanel;
    private javax.swing.JLabel reportdataLbl;
    private javax.swing.JSplitPane splitpane;
    private javax.swing.JButton transcriptButton;
    private javax.swing.JTextArea userProcessTextArea;
    private javax.swing.JTextArea userProcessTextArea2;
    // End of variables declaration//GEN-END:variables
}
